### ISSUE TITLE
Developer setup instructions

### ISSUE THREAD

**Issue by enkessler** [ccarrster/kraplow#100]
I want to take another crack at being able to build/test/tweak this project on my own but I'm not sure where to start, how to run/test the game, etc. Additionally, I'd rather not be bound to a particular IDE. That is, it's nice that you've source controlled some Eclipse settings but it's be better if others didn't have to use Eclipse.

- [x] Setup instructions
- [ ] Add Makefile or something similar to handle common tasks

**Comment by ccarrster** [comment]
Ant or Maven?

**Comment by enkessler** [comment]
No preference. As long as I can just type a few words in a command prompt, then I'm happy.

**Comment by enkessler** [comment]
Windows. Cross platform compatibility is preferable but the Git bash shell isn't a high bar, so whatever command line tools come built into that should be fine to use.

**Comment by enkessler** [comment]
Building and deploying works. The automator in me wants to be able to set an environmental variable for the deploy directory so that the build script will move the finished `.war` and I don't have to copy it myself.

It looks like you are using JUnit for testing? Is there any special way that they need to be kicked off? I tried just running them but I keep getting errors.

**Comment by enkessler** [comment]
@ccarrster I updated the task list. O:)

**Comment by enkessler** [comment]
I fixed my errors. I had a bad classpath for the tomcat server jar. An Ant task for testing would still be nice, though.
