### ISSUE TITLE
Show remaining Roles

### ISSUE THREAD

**Issue by enkessler** [ccarrster/kraplow#101]
Although a player can always search through the chat log in order to see which Roles have been eliminated, a visual list would be helpful. This would also let a player know which Roles are in the game to begin with, in case they have not memorized the order in which Roles are added as player count increases.

Perhaps a simple row of Role cards in the bottom right of the board area (below the box where card actions are chosen and to the right on the hand listing) that represent the Roles that are currently active in the game?

**Comment by ccarrster** [comment]
I like that... show remaining and eliminated roles.

**Comment by ccarrster** [comment]
Done
