### ISSUE TITLE
Jose Delgado Multiple Issues

### ISSUE THREAD

**Issue by Gorgrak** [ccarrster/kraplow#146]
1) The rules for him aren't stated explicitly enough and he's also missing from the [legend page](chriscarr.name:8080/westerncardgame/legend.html). Rulebook states he can use his ability **twice** per turn but can **only** draw them from his hand. It would be prudent to state this for users' benefit/understanding.
2) I was successfully able to use his ability on a "Silver" blue-border card but the card wasn't discarded like it should have been.
3) I was allowed to use my ability when I didn't have any cards in my hand. There is no "go-back" or undo function so the game stalled permanently when I was unable to choose any blue-border card to discard. I propose adding an "Undo" or "Cancel" button to his ability as well as any other character who has a choice to make when using their ability.

**Comment by ccarrster** [comment]
I implemented 1st edition of expansion. Will do 2nd now.

**Comment by ccarrster** [comment]
I fixed the issues. Not deployed yet.
