### ISSUE TITLE
Can't start game on self-hosted instance

### ISSUE THREAD

**Issue by hestela** [ccarrster/kraplow#162]
I was able to build the project with ant in linux (NixOS). Tomcat was able to serve the war file, but nothing happens when I click "Play A Game". Also the chat does't work.

I haven't made any modifications to my tomcat config, just added the webapp to the right directory.
Here's a link to a [screenshot](https://i.imgur.com/KBUC7lY.png)

I also tried using a docker container like in this [tutorial](https://aspetraining.com/resources/blog/deploying-your-first-web-app-to-tomcat-on-docker)

Not sure if have to do anything special to configure tomcat, first time using tomcat.

**Comment by hestela** [comment]
I ended up installing the latest jdk to use with eclipse and used the tomcat:9-jdk14-openjdk-oracle docker image to run my own instance of this repo. Great project btw.

**Comment by RyanPetrill** [comment]
I'm running into the same issue here. Followed all of the steps, but when I build locally I'm getting 404s when I reach the play screen:

(index):103 GET http://localhost:8080/westerncardgame/chat?messageType=AVAILABLEGAMES 404
The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

I haven't changed the naming at all of the files and I have the latest jdk/tomcat instances.

**Comment by hestela** [comment]
make sure the tomcat version is based on the jdk you are using. I also ended up using eclipse since it got mentioned in one of the other issues here, not sure if that's required or not. You also need to modify. Main thing on eclipse you have to do is set a library path in .classpath:
`<classpathentry kind="lib" path="F:/Program Files/Apache Software Foundation/Tomcat 6.0/lib/servlet-api.jar"/>`
i just changed it to the one in the repo to WebContent/WEB-INF/lib/servlet-api.jar 

i right clicked on the build.xml to build it as an ant project. And then deploy the war file on my tomcat docker image. i can post my eclipse project files if you need them

**Comment by RyanPetrill** [comment]
Ok, I can give that a try. It seems strange that it's running but just not able to make the API calls. 

I'm guessing it has to do with this part:

> The code uses an API.
> I called mine /chat - you can edit this in web.xml
> All of the code depends on /chat being there.
> You will need to change this in the getServletUrl function.
> Messages are sent as XML or strings.

But it's not very clear what I need to change in the getServletURL function

**Comment by hestela** [comment]
you shouldn't have to change getServletURL unless you plan to change 'chat' to something else. I'm not sure to the actual reason why chat doesn't get served. But it is related to this WEB-INF/web.xml
```
    <servlet-mapping>
        <servlet-name>Grapes</servlet-name>
        <url-pattern>/chat</url-pattern>
    </servlet-mapping>
```
